# Generated by Django 4.2.30 on 2026-09-30 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dealership_name', models.CharField(default='Marlow Motors', max_length=255)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('whatsapp', models.CharField(blank=True, max_length=50)),
                ('address', models.TextField(blank=True)),
                ('hours', models.TextField(blank=True)),
                ('social_links', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
